name: Build GUI Gnu-Linux

on:
  workflow_dispatch:
    inputs:
      tags:
        required: False
        description: 'test build tags'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: hedjour/pyinstaller-action-linux@main
      with:
        path: .
        spec: build_gui.spec

    - uses: actions/upload-artifact@v2
      with:
        name: ecm_linux
        path: ./dist/linux