name: Test Build GUI bin with Pyinstaller

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'test build tags'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y libwxbase3.0-0v5 libwxgtk-media3.0-gtk3-0v5 libwxgtk-webview3.0-gtk3-0v5 \
          libwxgtk3.0-gtk3-0v5 python3-wxgtk-media4.0 python3-wxgtk-webview4.0 python3-wxgtk4.0

    - name: Install Gooey
      run: |
          pip install gooey
