name: Build GUI exe with Pyinstaller

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'test build tags'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: build_gui.spec

    - uses: actions/upload-artifact@v2
      with:
        name: ecm_win
        path: ./dist/windows
